language: r
cache: packages

r:
  - oldrel
  - release 
  - devel

r_packages:
  - covr
r_github_packages:
  - csgillespie/benchmarkme-data
  
addons:
  apt:
    packages:
      - libgsl0-dev # For RCppZigg

## Only run covr on release
after_success:
  - Rscript -e "if(length(grep('2\$', ${TRAVIS_JOB_NUMBER}))) covr::codecov()";
  - Rscript -e "if(length(grep('2\$', ${TRAVIS_JOB_NUMBER}))) Sys.setenv('R_COMPILE_PKGS' = 0); install.packages('benchmarkme')";
  - Rscript -e "if(length(grep('2\$', ${TRAVIS_JOB_NUMBER}))) capture.output(benchmark::benchmark_std)";
  - Rscript -e "if(length(grep('2\$', ${TRAVIS_JOB_NUMBER}))) res = benchmarkme::benchmark_std(); benchmarkme::upload_results(res)"
  - Rscript -e "if(length(grep('2\$', ${TRAVIS_JOB_NUMBER}))) res = benchmarkme::benchmark_io(); benchmarkme::upload_results(res)"

notifications:
  email:
    on_success: change
    on_failure: change
